nv: 784
nh: 100
batch_size: 400
epochs: 500
lr: 0.009
t: 500
gamma: 0.007
gpu_usage: true
dev: 2
optType: "Adam"
dataset: "MNIST"
scale: 3.14
type: "fixed"
data_path: "/home/javier/Projects/RKM/Results/XY32/XY32.jld"
model_path: "/home/javier/Projects/RKM/Results/models"
model_name: "model2"
maxmem: "5GiB"