nv: 784
nh: 100
batch_size: 400
epochs: 100
lr: 0.001
t: 100
gamma: 0.001
gpu_usage: false
dev: 0
optType: "Adam"
dataset: "MNIST"
data_path: "/home/javier/Projects/RKM/Results/XY32/XY32.jld"
model_path: "/home/javier/Projects/RKM/Results/models"
model_name: "rkm_CD_cpu"
maxmem: "20GiB"